Индивидуальное задание 1

Условие:

 Дана целочисленная квадратная матрица. 
Определить:
1)сумму элементов в тех столбцах, которые не содержат отрицательных элементов;
2)минимум среди сумм модулей элементов диагоналей, параллельных побочной диагонали
матрицы.

In [ ]:
Решение:

In [15]:
import numpy as np
m=np.matrix('0,2,7,-9;3,5,4,6;22,17,-8,30;44,50,0,11')
print(m)

[[ 0  2  7 -9]
 [ 3  5  4  6]
 [22 17 -8 30]
 [44 50  0 11]]


In [20]:
cols = [0, 1, 2, 3]
a = m[:, cols] > 0
b = m.sum(axis=0) > 0
np.sum(b)

4